### ISSUE TITLE
GET: Highlight the selected train

### ISSUE THREAD

**Issue by El-Youssef** [osrd-project/osrd-ui#291]
Description
Quand un utilisateur sélectionne un train dans la liste des trains, le train sélectionné est mis en surbrillance dans le GET.

Acceptance criteria
- [ ] Le train sélectionné dans la liste des trains est mis en surbrillance dans le GET.

**Comment by Math-R** [comment]
https://github.com/OpenRailAssociation/osrd-ui/pull/293

**Comment by Math-R** [comment]
Need to release osrd-ui
