### ISSUE TITLE
Date picker is in english even when the interface is in french

### ISSUE THREAD

**Issue by axrolld** [osrd-project/osrd-ui#593]
### What happened?

![image](https://github.com/user-attachments/assets/746ab69d-3541-4ce6-993d-c6ff6eae5fe5)

### What did you expect to happen?

A french translation for our favorite 🐸 

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Deployed Storybook

### On which browser the bug occurs?

Google Chrome

**Comment by Arthur-Lefebvre** [comment]
Duplicates https://github.com/OpenRailAssociation/osrd-ui/issues/759
