### ISSUE TITLE
trackoccupancydiagram: add selected train display

### ISSUE THREAD

**Issue by Yohh** [osrd-project/osrd-ui#740]
### Description and goal

according to the mockup, the selected train ID is compared to the zone occupancy, which is highlighted
https://www.sketch.com/s/50744654-4631-4fae-8e7c-7eb22dfadc1a

### Acceptance criteria

- [x] the zone and the train name are both in a yellow rect
- [x] the white border displayed only for the zone rect and the train name

**Comment by clarani** [comment]
I don't really understand the 2nd AC, can you explain what is expected ?

**Comment by Yohh** [comment]
I changed it, is it better?

**Comment by clarani** [comment]
Yep, perfect, thanks 🤩
