### ISSUE TITLE
manchette with space-time chart: Panning breaks

### ISSUE THREAD

**Issue by Castavo** [osrd-project/osrd-ui#746]
### What happened?

When having zoomed the manchette, panning the space-time chart breaks the manchette: the menu moves, and last waypoint isn't aligned with the chart

https://github.com/user-attachments/assets/54066a99-f41a-4450-bc3e-76684855be45

### What did you expect to happen?

I expect the menu to always stay at the bottom, and the waypoints to always be aligned.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to https://openrailassociation.github.io/osrd-ui/?path=/story/manchette-with-spacetimechart-rendering--default
2. Zoom on the manchette a little
3. Pan the chart around
4. witness

### On which environments the bug occurs?

Deployed Storybook

### On which browser the bug occurs?

Firefox

**Comment by SharglutDev** [comment]
This should be fixed with the next osrd-ui release. I'll keep this in mind.

**Comment by Castavo** [comment]
Indeed, can't reproduce
