### ISSUE TITLE
[icons] Icons for errors on pathfinding

### ISSUE THREAD

**Issue by sim51** [osrd-project/osrd-ui#96]
In my feature related to path finding constraints, I have to display icons for : 
- electrification (a flash)
- gauge (a tunnel with a train)
- signalization (traffic light ?)
- See on the map 

![image](https://github.com/OpenRailAssociation/osrd-ui/assets/231657/3691069a-f765-4753-ab7d-7609253ace89)

**Comment by thibautsailly** [comment]
If I click on "See on the map", does it frame and centers the object in the map view box?

**Comment by thibautsailly** [comment]
The flash icon already exists in the initial icon set under the name of `zap-fill`.

[Zap.zip](https://github.com/user-attachments/files/16144213/Zap.zip)

**Comment by thibautsailly** [comment]
Here is the gauge icon.
[Gauge.zip](https://github.com/user-attachments/files/16144231/Gauge.zip)

**Comment by sim51** [comment]
For your question about the map button : yes

**Comment by sim51** [comment]
For the zap, sorry I missed it.

**Comment by thibautsailly** [comment]
See on map: use the existing "location" icon.


![Image](https://github.com/OpenRailAssociation/osrd-ui/assets/870509/e16e0963-3e04-4a08-bb74-74c7b88018e6)

**Comment by thibautsailly** [comment]
Here is the signals icon
[Signals.zip](https://github.com/user-attachments/files/16158344/Signals.zip)
